//! niiLISP interpreter command-line entry point.
//!
//! Usage:
//!
//! ```text
//! niilisp FILE          run a script (or start a REPL if no FILE)
//! niilisp -e EXPR       evaluate EXPR
//! niilisp -             read a script from standard input
//! niilisp --version     print the version
//! niilisp --help        print usage
//! ```

use std::io::Read;
use std::process::ExitCode;

use niilisp::{Interp, Signal};

const USAGE: &str = "\
niilisp - a re-implementation of the newLISP dialect

USAGE:
    niilisp [FILE]        Run a script file
    niilisp -e EXPR       Evaluate an expression
    niilisp -             Read and run a script from standard input
    niilisp               Start an interactive REPL

OPTIONS:
    -e EXPR              Evaluate EXPR and exit
    -h, --help          Print this help
    -V, --version       Print version, copyright, and a license pointer
    license             Print the open-source licenses of niilisp and its deps
";

/// Open-source license notices for niilisp (GPL-3.0-or-later) and every bundled
/// Rust dependency, generated by `cargo about` and embedded so the `license`
/// command works for a binary-only distribution with no accompanying files.
const THIRD_PARTY_LICENSES: &str = include_str!("../THIRD-PARTY-LICENSES.md");

/// The `--version` banner — compact, php/ruby style: name + version + build
/// stamp + repo, copyright, and a one-line pointer to `license`.
fn version_text() -> String {
    format!(
        concat!(
            "niilisp {} ({} revision {}) - {}\n",
            "Copyright (c) {}\n",
            "    Free software under the GNU GPL v3 or later; see LICENSE.md and COPYING.\n",
            "    Run `niilisp license` for all bundled dependencies and their licenses.",
        ),
        env!("CARGO_PKG_VERSION"),
        env!("NIILISP_BUILD_DATE"),
        env!("NIILISP_GIT_REV"),
        env!("CARGO_PKG_REPOSITORY"),
        env!("CARGO_PKG_AUTHORS"),
    )
}

/// The `license` output: a header plus niilisp's own GPL notice and every
/// bundled dependency's notice, embedded so it works with no accompanying files.
fn license_text() -> String {
    format!(
        "niilisp {} — open source licenses\n{}\n\n{THIRD_PARTY_LICENSES}",
        env!("CARGO_PKG_VERSION"),
        env!("CARGO_PKG_REPOSITORY"),
    )
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    let interp = Interp::new();
    interp.set_main_args(args.clone());

    match args.get(1).map(String::as_str) {
        None => {
            niilisp::repl::run(&interp);
            ExitCode::SUCCESS
        }
        Some("-h") | Some("--help") => {
            print!("{}", USAGE);
            ExitCode::SUCCESS
        }
        Some("-V") | Some("--version") | Some("version") => {
            println!("{}", version_text());
            ExitCode::SUCCESS
        }
        Some("license") | Some("licenses") => {
            print!("{}", license_text());
            ExitCode::SUCCESS
        }
        Some("-e") => match args.get(2) {
            Some(expr) => run_or_exit(&interp, expr.as_bytes()),
            None => {
                eprintln!("niilisp: -e requires an expression");
                ExitCode::from(2)
            }
        },
        Some("-") => {
            let mut src = Vec::new();
            if let Err(e) = std::io::stdin().read_to_end(&mut src) {
                eprintln!("niilisp: cannot read stdin: {}", e);
                return ExitCode::from(2);
            }
            run_or_exit(&interp, &src)
        }
        Some(flag) if flag.starts_with('-') => {
            eprintln!("niilisp: unknown option '{}'\n\n{}", flag, USAGE);
            ExitCode::from(2)
        }
        Some(path) => match std::fs::read(path) {
            Ok(src) => run_or_exit(&interp, &src),
            Err(e) => {
                eprintln!("niilisp: cannot read {}: {}", path, e);
                ExitCode::from(2)
            }
        },
    }
}

/// Run a whole source, reporting a runtime error to stderr with exit code 1.
/// A top-level `(exit code)` maps to that process exit code (ADR-0040), so the
/// CLI's observable exit behaviour is unchanged.
fn run_or_exit(interp: &Interp, src: &[u8]) -> ExitCode {
    match run_source(interp, src) {
        Ok(()) => ExitCode::SUCCESS,
        Err(Signal::Exit(code)) => ExitCode::from(code as u8),
        Err(sig) => {
            eprintln!("niilisp: {}", niilisp::signal_message(interp, sig));
            ExitCode::FAILURE
        }
    }
}

fn run_source(interp: &Interp, src: &[u8]) -> Result<(), Signal> {
    let forms = niilisp::read_forms(interp, src).map_err(Signal::error)?;
    for form in &forms {
        interp.eval(form)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn version_banner_has_name_version_stamp_and_license_pointer() {
        let v = version_text();
        assert!(v.starts_with(&format!("niilisp {} (", env!("CARGO_PKG_VERSION"))));
        assert!(v.contains("revision "), "must carry a build revision:\n{v}");
        assert!(v.contains("GNU GPL v3"), "must state the license:\n{v}");
        assert!(
            v.contains("niilisp license"),
            "must point at the license command:\n{v}"
        );
    }

    #[test]
    fn license_text_includes_own_and_third_party_notices() {
        let l = license_text();
        assert!(l.contains("open source licenses"));
        // The embedded third-party notices are present.
        assert!(l.contains("GNU General Public License") && l.contains("MIT License"));
    }
}
